[package]
name = "libh3"
version = "0.1.0"
authors = ["Rusty Conover <rusty@conover.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libh3-sys = "0.1.1"
float-cmp = "0.6.0"
