[package]
name = "libh3"
version = "0.2.0"
authors = ["Rusty Conover <rusty@conover.me>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/rustyconover/libh3.git"
description = "Safe Rust Bindings to Uber's Hexagonal Hierarchical Spatial Index - H3"

[build-dependencies]
bindgen = "0.71.1"
directories = "6.0.0"

[dependencies]
static_assertions = "1.1.0"
